### ISSUE TITLE
Turn mods directory into a github repo with submodules (was: orphaned/not-updated mods)

### ISSUE THREAD

**Issue by obl3pplifp** [BlockySurvival/issue-tracker#34]
In order to make the server more maintainable (and testable, and recoverable) the mods folder should be turned into a github repo composed of submodules, one corresponding to each mod. 

This issue lists mods which have changes inside them that aren't part of an existing repo. Once these are resolved, the master mod repo can be created. 

- [ ] ambience (unstaged changes to reduce amount of noise)
- [ ] arctic_life (unstaged changes to disable penguin and fiddle walrus)
- [ ] areas https://github.com/BlockySurvival/areas.git
- [ ] areasprotector (unstaged changes)
- [ ] bowlingball https://github.com/thetaepsilon-gamedev/bowlingball.git
- [ ] caverealms (because of mapgen issues) https://github.com/HeroOfTheWinds/minetest-caverealms.git
- [ ] display_modpack https://github.com/xerox123official/display_modpack.git
- [x] extra NONE (change: disable ore recovery)
- [ ] goldtools NONE
- [x] holidays (I've taken this over)
- [ ] locked_travelnet (unstaged changes to fix mod.conf)
- [ ] locks (unstaged changes to disable some things)
- [ ] mailbox NONE
- [ ] main NONE (billy's marble/stone/honey bottle mod)
- [ ] maptools (unstaged changes: various; see https://github.com/obl3pplifp/BlS-issue-tracker/issues/60)
- [ ] memorandum: (unstaged change to prevent crash)
- [ ] mobs_animal (unstaged change to let panda eat papyrus)
- [ ] mobs_birds (unstaged change to fix gull model typo)
- [ ] moreplants https://github.com/BlockySurvival/moreplants.git
- [x] moretrees https://github.com/BlockySurvival/moretrees.git
- [x] nogrief NONE -> https://github.com/obl3pplifp/minetest-nogrief
- [ ] no_guests NONE
- [ ] skinsdb NONE (modpack; u_skins)
- [ ] spawn_command NONE
- [ ] sponge https://github.com/thetaepsilon-gamedev/minetest-mod-sponges.git
- [ ] snowdrift (unstaged changes to reduce the amount of rain)
- [ ] stamina (unstaged change to fiddle stamina costs; see https://github.com/obl3pplifp/BlS-issue-tracker/issues/76)
- [ ] streetlamps NONE
- [ ] streetsconcrete NONE
- [ ] streetsmod NONE
- [x] technic_chests NONE -> https://github.com/minetest-mods/technic
- [x] teleport-request https://github.com/BlockySurvival/teleport-request.git
- [ ] tubelib (unstaged change to prevent machines from turning into "defect dummy"s; see https://github.com/obl3pplifp/BlS-issue-tracker/issues/12)
- [ ] xdecor (unstaged chess game change to prevent server crash; see https://github.com/obl3pplifp/BlS-issue-tracker/issues/47)

**Comment by fluxionary** [comment]
I finished this. See https://github.com/BlockySurvival/bls_mods
